### ISSUE TITLE
Projects have been deleted server throwing error

### ISSUE THREAD

**Issue by rrw357719** [SelfhostedPro/Yacht#352]
**Describe the bug**
Projects had been created to run docker stacks. The projects tab on the home page responds with the following error:

Internal Server Error: undefined 

**Expected behavior**
Projects that have been built are available.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Yacht Version: v0.0.6-alpha-2021-02-25--15

**Additional context**

** Logs **
 yacht
View and Manage yacht
Logs
 INFO:      - "GET /api/apps/Deemix/processes HTTP/1.1" 200 OK
 
 INFO:      - "GET /api/apps/Deemix/processes HTTP/1.1" 200 OK
 
 INFO:     None - "WebSocket /api/apps/Deemix/livelogs" [accepted]
 
 INFO:     None - "WebSocket /api/apps/Deemix/stats" [accepted]
 
 INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
 
 INFO:      - "GET /api/compose/ HTTP/1.1" 500 Internal Server Error
 
 ERROR:    Exception in ASGI application
 
 Traceback (most recent call last):
 
   File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
 
     result = await app(self.scope, self.receive, self.send)
 
   File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
 
     return await self.app(scope, receive, send)
 
   File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
 
     await super().__call__(scope, receive, send)
 
   File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
 
     await self.middleware_stack(scope, receive, send)
 
   File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
 
     raise exc from None
 
   File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
 
     await self.app(scope, receive, _send)
 
   File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
 
     raise exc from None
 
   File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
 
     await self.app(scope, receive, sender)
 
   File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
 
     await route.handle(scope, receive, send)
 
   File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
 
     await self.app(scope, receive, send)
 
   File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
 
     response = await func(request)
 
   File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
 
     raw_response = await run_endpoint_function(
 
   File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
 
     return await run_in_threadpool(dependant.call, **values)
 
   File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
 
     return await loop.run_in_executor(None, func, *args)
 
   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
 
     result = self.fn(*self.args, **self.kwargs)
 
   File "./api/routers/compose.py", line 22, in get_projects
 
     return get_compose_projects()
 
   File "./api/actions/compose.py", line 191, in get_compose_projects
 
     if loaded_compose.get("volumes"):
 
 AttributeError: 'str' object has no attribute 'get'
 
 INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
 
 INFO:      - "GET /api/apps/yacht HTTP/1.1" 200 OK
 
 INFO:      - "GET /api/apps/yacht/processes HTTP/1.1" 200 OK
 
 INFO:      - "GET /api/apps/yacht HTTP/1.1" 200 OK
 
 INFO:      - "GET /api/apps/yacht/processes HTTP/1.1" 200 OK
 
 INFO:     None - "WebSocket /api/apps/yacht/livelogs" [accepted]
 
 INFO:     None - "WebSocket /api/apps/yacht/stats" [accepted]

**Comment by SelfhostedPro** [comment]
Is this for the built in templates or a custom template?

**Comment by SelfhostedPro** [comment]
Ah I misread. Try the devel tag. I've since fixed that error as it relates to volumes not being defined in services.

**Comment by rrw357719** [comment]
The projects are just several containers I wish to always run together. The containers are still up and running with no issues. The projects they refer to are missing.

________________________________

**Comment by SelfhostedPro** [comment]
Could you check to see if there are any folders for the now deleted projects? I do believe the devel tag would fix this. You can use it just adding `:devel` to the end of the docker command you use to deploy yacht.

**Comment by rrw357719** [comment]
The instance in being deployed from within Open Media Vault i am not able to add the additional tag

**Comment by rrw357719** [comment]
the folder for the projects have been deleted.

**Comment by SelfhostedPro** [comment]
Yes, the devel tag will resolve your issue. I haven't merged it into master yet but plan to soon. Can you paste a copy of the docker-compose.yaml you're trying to use? I could suggest changes to get it to work with the current version if you're having trouble using the devel tag.

**Comment by rrw357719** [comment]
ran the new instance with the devel tag the projects tab still presents with the same error

**Comment by SelfhostedPro** [comment]
What is the end goal? Can you run the `tree` command in your projects folder?

I believe there may be a malformed docker-compose in it somewhere as the error refers to an issue loading/parsing a docker-compose file.

**Comment by rrw357719** [comment]
the end goal is to have the projects functioning properly so that on the fly edits can be made to images grouped in the stacks. At this point i have no way to bring the members of the stacks back up as they are spun up using the projects template that had been built. The have been no changes to the yacht docker or any additional dockers within the last 48 hours.

**Comment by rrw357719** [comment]
when an attempt is made to create a new project the same error is thrown when submitting the info

**Comment by rrw357719** [comment]
File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
 

     await self.app(scope, receive, sender)
 

   File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
 

     await route.handle(scope, receive, send)
 

   File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
 

     await self.app(scope, receive, send)
 

   File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
 

     response = await func(request)
 

   File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
 

     raw_response = await run_endpoint_function(
 

   File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
 

     return await run_in_threadpool(dependant.call, **values)
 

   File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
 

     return await loop.run_in_executor(None, func, *args)
 

   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
 

     result = self.fn(*self.args, **self.kwargs)
 

   File "./api/routers/compose.py", line 22, in get_projects
 

     return get_compose_projects()
 

   File "./api/actions/compose.py", line 191, in get_compose_projects
 

     if loaded_compose.get("volumes"):
 

 AttributeError: 'str' object has no attribute 'get'
 

 INFO:     None - "WebSocket /api/apps/stats" [accepted]
 

 INFO:      - "GET /api/auth/me HTTP/1.1" 200 OK
 

 INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
 

 INFO:      - "GET /api/apps/yacht HTTP/1.1" 200 OK
 

 INFO:      - "GET /api/apps/yacht HTTP/1.1" 200 OK
 

 INFO:      - "GET /api/apps/yacht/processes HTTP/1.1" 200 OK
 

 INFO:      - "GET /api/apps/yacht/processes HTTP/1.1" 200 OK
 

 INFO:     None - "WebSocket /api/apps/yacht/livelogs" [accepted]
 

 INFO:     None - "WebSocket /api/apps/yacht/stats" [accepted]
 

 INFO:      - "GET /api/apps/yacht HTTP/1.1" 200 OK
 

 INFO:      - "GET /api/resources/networks/ HTTP/1.1" 200 OK
 

 INFO:      - "GET /api/compose/ HTTP/1.1" 500 Internal Server Error
 

 ERROR:    Exception in ASGI application
 

 Traceback (most recent call last):
 

   File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
 

     result = await app(self.scope, self.receive, self.send)
 

   File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
 

     return await self.app(scope, receive, send)
 

   File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
 

     await super().__call__(scope, receive, send)
 

   File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
 

     await self.middleware_stack(scope, receive, send)
 

   File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
 

     raise exc from None
 

   File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
 

     await self.app(scope, receive, _send)
 

   File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
 

     raise exc from None
 

   File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__

**Comment by rrw357719** [comment]
issue has been resolved 
deleted the most recent project from the _data file
/srv/dev-disk-by-uuid-f27c399a-e7ca-4381-913a-02b60c33afc9/dockers/share/volumes/yacht/_data/compose/

thank you for you assistance outstanding product!!!!

**Comment by SelfhostedPro** [comment]
Glad that solved it for you. I'll work on some better error handling for that and leave this ticket open as a reminder. Thanks for reaching out with your issue!

**Comment by SelfhostedPro** [comment]
Fix has been published to the latest release. If there are any issues with it, comment here and I'll reopen.
