### ISSUE TITLE
[Bug Report] "Error 500: undefined" error if host port is already in use

### ISSUE THREAD

**Issue by gleniat** [SelfhostedPro/Yacht#397]
**Describe the bug**
Open any template with 80 and 443 host ports set. If the ports are already in use, deploy stage fails with Error 500: unknown error. This is hard to debug, the error text should be useful.

**To Reproduce**
On Networking tab, use a port which is already in use. Final step will fail.

**Expected behavior**
Error contains a useful message.

**Desktop (please complete the following information):**
 - OS: Debian
 - Yacht v0.0.7-alpha

**Log**
```
INFO:      - "POST /api/apps/deploy HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/lib/python3.8/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/./api/routers/apps.py", line 66, in deploy_app
    return actions.deploy_app(template=template)
  File "/./api/actions/apps.py", line 195, in deploy_app
    status_code=exc.response.status_code, detail=exc.explanation
AttributeError: 'AttributeError' object has no attribute 'response'
```

**Comment by SelfhostedPro** [comment]
Does it give any more details in the logs? Previously this gave a more detailed error.

**Comment by gleniat** [comment]
I have added the log. Please add how to obtain the log to the Yacht documentation. I was searching it in the host filesystem until I realized that yacht runs in its own container. :-)

**Comment by skluthe** [comment]
> I have added the log. Please add how to obtain the log to the Yacht documentation. I was searching it in the host filesystem until I realized that yacht runs in its own container. :-)

You can also use the help button in the Yacht container to get the log and docker inspect for the container. May be a good idea to output the log to the config directory as well.

**Comment by SelfhostedPro** [comment]
A fix for this is building in the :devel tag now. Should be ready in an hour or two for testing.

**Comment by SelfhostedPro** [comment]
Fix has been published to the latest release.
