### ISSUE TITLE
[Bug Report] No module named 'api' running on arm

### ISSUE THREAD

**Issue by Lerosen** [SelfhostedPro/Yacht#443]
**Describe the bug**

**To Reproduce**
I just started the container as described in the docs. When logging in the frontend displays the error "404 - not found".
The exact image is `selfhostedpro/yacht@sha256:06020b35df957d42d2d9c1a55bb7648dbc14262e1c147a12556ede66f657445c` which is the arm version created `2021-05-31T17:08:59.837365265Z`.
I also tried other tags with the same reult, on my windows machine it works flawless.

**Expected behavior**
I expect it to work :)

**Screenshots**
![image](https://user-images.githubusercontent.com/20213986/151695932-476b80c9-4d2b-478f-9e64-68363cb0c411.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - Browser: MS edge
 - Docker version: Docker version 19.03.12, build 48a6621

** Logs **
```
2022-01-30T07:43:05.054659620Z Traceback (most recent call last):
2022-01-30T07:43:05.054903495Z   File "/usr/bin/uvicorn", line 8, in <module>
2022-01-30T07:43:05.055044537Z     sys.exit(main())
2022-01-30T07:43:05.055165620Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2022-01-30T07:43:05.055251287Z     return self.main(*args, **kwargs)
2022-01-30T07:43:05.055326162Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
2022-01-30T07:43:05.055403745Z     rv = self.invoke(ctx)
2022-01-30T07:43:05.055475954Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2022-01-30T07:43:05.055547454Z     return ctx.invoke(self.callback, **ctx.params)
2022-01-30T07:43:05.055611204Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2022-01-30T07:43:05.055680495Z     return callback(*args, **kwargs)
2022-01-30T07:43:05.055749537Z   File "/usr/lib/python3.8/site-packages/uvicorn/main.py", line 339, in main
2022-01-30T07:43:05.055817829Z     run(**kwargs)
2022-01-30T07:43:05.055879579Z   File "/usr/lib/python3.8/site-packages/uvicorn/main.py", line 362, in run
2022-01-30T07:43:05.055945329Z     server.run()
2022-01-30T07:43:05.056004495Z   File "/usr/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
2022-01-30T07:43:05.056067579Z     loop.run_until_complete(self.serve(sockets=sockets))
2022-01-30T07:43:05.056390829Z   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
2022-01-30T07:43:05.056524245Z   File "/usr/lib/python3.8/site-packages/uvicorn/main.py", line 397, in serve
2022-01-30T07:43:05.056617412Z     config.load()
2022-01-30T07:43:05.056695995Z   File "/usr/lib/python3.8/site-packages/uvicorn/config.py", line 278, in load
2022-01-30T07:43:05.056769329Z     self.loaded_app = import_from_string(self.app)
2022-01-30T07:43:05.056843829Z   File "/usr/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
2022-01-30T07:43:05.056914537Z     raise exc from None
2022-01-30T07:43:05.056984787Z   File "/usr/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
2022-01-30T07:43:05.057058579Z     module = importlib.import_module(module_str)
2022-01-30T07:43:05.057136287Z   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2022-01-30T07:43:05.057212704Z     return _bootstrap._gcd_import(name[level:], package, level)
2022-01-30T07:43:05.057286495Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-01-30T07:43:05.057366120Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-01-30T07:43:05.057443912Z   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2022-01-30T07:43:05.057516995Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-01-30T07:43:05.057591579Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-01-30T07:43:05.057662787Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-01-30T07:43:05.057746079Z   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2022-01-30T07:43:05.057831495Z ModuleNotFoundError: No module named 'api'
```

**Comment by SelfhostedPro** [comment]
Can you try using the :devel tag? Just add it to the end of the `docker run` command in the docks like so: `selfhostedpro/yacht:devel`

**Comment by Lerosen** [comment]
Thanks for your reponse, I actually already tried that.Same results with `devel` and `v0.0.7-alpha-hf-1`.

**Comment by SelfhostedPro** [comment]
What about :nightly? I have a pi I can test on this week to see what’s up.

**Comment by Lerosen** [comment]
Same reulst for the gighly tag. But I just tried it on another board (ARM) and there it worked flawlessly, so there seems to be an issue on my side (even if I find the error very weird)... Closing this for now.

**Comment by SelfhostedPro** [comment]
What hardware were you running on at first?

**Comment by Lerosen** [comment]
It was a bananapi m2 berry with ARMv7 Cortex cpu. This one https://wiki.banana-pi.org/Banana_Pi_BPI-M2_Berry

**Comment by Lerosen** [comment]
hm, a day later it magically just works and the error disappeared, I just left the container running... Thanks for your support!

**Comment by SelfhostedPro** [comment]
Very strange! Glad it’s working for you now. Let me know if you have anything else pop up.
