### ISSUE TITLE
[Bug Report] Dashboard is empty

### ISSUE THREAD

**Issue by jvalrog** [SelfhostedPro/Yacht#597]
**Describe the bug**
The API is not responding on `api/apps/stats`.

Firefox shows this error: **NS_ERROR_NET_PARTIAL_TRANSFER**

while Chrome says: **GET http://rpi.local:8000/api/apps/stats net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)**

I think it's not a problem with the tokens because it happens as soon as I log in.

**Screenshots**
![image](https://github.com/SelfhostedPro/Yacht/assets/456311/22349eaa-6668-4d47-96e5-a8ea672de943)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser firefox / chrome
 - Yacht v0.0.7-alpha-2023-01-12--05

**Logs**
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 176, in __call__
    await run_until_first_complete(
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 199, in stream_response
    async for data in self.body_iterator:
  File "/./api/actions/apps.py", line 528, in all_stat_generator
    async for event in merged:
  File "/usr/lib/python3.8/site-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
  File "/./api/actions/apps.py", line 503, in stat_generator
    current_stats = await process_app_stats(line, app_name)
  File "/./api/actions/apps.py", line 537, in process_app_stats
    mem_current = line["memory_stats"]["usage"]
KeyError: 'usage'
```

**Comment by djripcord** [comment]
Seeing this as well. A browser refresh or logout/login usually fixes the issue.

**Comment by rafsko1** [comment]
Exactly same issue I have. Did you manage sort it out?

**Comment by NolandTech** [comment]
Same issue

**Comment by SelfhostedPro** [comment]
If you're on arm and don't follow the instructions for modifying cmdline.txt you'll run into this. The `devel` image also has some fixes related to this.

https://yacht.sh/docs/Installation/ARM
