### ISSUE TITLE
[Bug Report] Yacht Can`t show anything container

### ISSUE THREAD

**Issue by AkarinLiu** [SelfhostedPro/Yacht#598]
**Describe the bug**

**To Reproduce**
1. Create Container
2. Access Yacht Panel

**Expected behavior**

**Screenshots**
![图片](https://github.com/SelfhostedPro/Yacht/assets/58081491/3e9229b1-c670-4b59-94ce-90675252de4f)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Mozilla Firefox ESR
 - Yacht Version: v0.0.7-alpha-2021-05-31--16

**Additional context**

** Logs **
Add any relevant logs (from the yacht docker container or from your browser console)
```
root@raspberrypi:~# docker logs yacht
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 31-migrate: executing... 
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'template_variables'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_variables_replacement' on '['replacement']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_variables_variable' on '['variable']'
INFO  [alembic.autogenerate.compare] Detected added table 'templates'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_templates_title' on '['title']'
INFO  [alembic.autogenerate.compare] Detected added table 'user'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_email' on '['email']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_id' on '['id']'
INFO  [alembic.autogenerate.compare] Detected added table 'apikeys'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_id' on '['id']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_jti' on '['jti']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_key_name' on '['key_name']'
INFO  [alembic.autogenerate.compare] Detected added table 'template_item'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_item_name' on '['name']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_item_title' on '['title']'
--- MODELS ---
Generating /alembic/versions/ec7acf382a3d_automated_db_upgrade.py ...  done
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> ec7acf382a3d, automated db upgrade
--- MODELS ---
[cont-init.d] 31-migrate: exited 0.
[cont-init.d] 32-env: executing... 
Replacing env constants in JS
Processing /app/js/app.1d365aa7.js ...
Processing /app/js/app.1d365aa7.js.map ...
Processing /app/index.html ...
[cont-init.d] 32-env: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO:     Started server process [314]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on unix socket /tmp/gunicorn.sock (Press CTRL+C to quit)
Secret key generated
Secret key exists
DISABLE_AUTH = False (<class 'bool'>)
No Users. Creating the default user.
No Variables yet!
INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
INFO:      - "GET /api/apps/ HTTP/1.1" 401 Unauthorized
INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
INFO:      - "POST /api/auth/login HTTP/1.1" 200 OK
INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 176, in __call__
    await run_until_first_complete(
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 199, in stream_response
    async for data in self.body_iterator:
  File "/./api/actions/apps.py", line 528, in all_stat_generator
    async for event in merged:
  File "/usr/lib/python3.8/site-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
  File "/./api/actions/apps.py", line 503, in stat_generator
    current_stats = await process_app_stats(line, app_name)
  File "/./api/actions/apps.py", line 537, in process_app_stats
    mem_current = line["memory_stats"]["usage"]
KeyError: 'usage'
INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 176, in __call__
    await run_until_first_complete(
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 199, in stream_response
    async for data in self.body_iterator:
  File "/./api/actions/apps.py", line 528, in all_stat_generator
    async for event in merged:
  File "/usr/lib/python3.8/site-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
  File "/./api/actions/apps.py", line 503, in stat_generator
    current_stats = await process_app_stats(line, app_name)
  File "/./api/actions/apps.py", line 537, in process_app_stats
    mem_current = line["memory_stats"]["usage"]
KeyError: 'usage'
INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 176, in __call__
    await run_until_first_complete(
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 199, in stream_response
    async for data in self.body_iterator:
  File "/./api/actions/apps.py", line 528, in all_stat_generator
    async for event in merged:
  File "/usr/lib/python3.8/site-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
  File "/./api/actions/apps.py", line 503, in stat_generator
    current_stats = await process_app_stats(line, app_name)
  File "/./api/actions/apps.py", line 537, in process_app_stats
    mem_current = line["memory_stats"]["usage"]
KeyError: 'usage'
INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
INFO:      - "GET /api/auth/me HTTP/1.1" 200 OK
INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 176, in __call__
    await run_until_first_complete(
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/usr/lib/python3.8/site-packages/sse_starlette/sse.py", line 199, in stream_response
    async for data in self.body_iterator:
  File "/./api/actions/apps.py", line 528, in all_stat_generator
    async for event in merged:
  File "/usr/lib/python3.8/site-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
  File "/./api/actions/apps.py", line 503, in stat_generator
    current_stats = await process_app_stats(line, app_name)
  File "/./api/actions/apps.py", line 537, in process_app_stats
    mem_current = line["memory_stats"]["usage"]
KeyError: 'usage'
Resource ID was not provided
INFO:      - "GET /api/settings/check/update HTTP/1.1" 400 Bad Request
```

**Comment by AkarinLiu** [comment]
![图片](https://github.com/SelfhostedPro/Yacht/assets/58081491/ff2e0455-625f-49ed-b3d3-7b49258064f9)

**Comment by SelfhostedPro** [comment]
https://yacht.sh/docs/Installation/ARM

Please follow instructions here for arm devices.

**Comment by wickedyoda** [comment]
Please update or close the ticket as resolved.
